# Generated by Django 4.0.1 on 2022-02-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
