# Generated by Django 4.0.1 on 2022-02-22 16:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='herbs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
    ]
