# Generated by Django 4.0.1 on 2022-02-22 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0006_user_proteins_user_spices_alter_user_herbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='herbs',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=3), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='proteins',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=3), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='spices',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=3), default=list, null=True, size=None),
        ),
    ]
